### ISSUE TITLE
Version 2.3.0 produces erroneous results for some queries

### ISSUE THREAD

**Issue by isaisabel** [oasis-open/cti-taxii-client#104] opened 2021-09-22 16:08 UTC
`taxii2-client` version 2.3.0 produces some erroneous results when querying the ATT&CK TAXII server that are not observed in version 2.2.2. The following test script demonstrates this issue:

```python
from stix2 import TAXIICollectionSource, Filter
from taxii2client.v20 import Server, Collection

collections = {
    "enterprise_attack": "95ecc380-afe9-11e4-9b6c-751b66dd541e",
    "pre_attack": "062767bd-02d2-4b72-84ba-56caef0f8658",
    "mobile_attack": "2f669986-b40b-4423-b720-4396ca6a462b",
    "ics": "02c3ef24-9cd4-48f3-a99f-b74ce24f1d34"
}

# connect to the TAXII server
collection = Collection(f"https://cti-taxii.mitre.org/stix/collections/{collections['enterprise_attack']}/")
tc_src = TAXIICollectionSource(collection)

print(len(tc_src.query([Filter('type','=', 'attack-pattern'), Filter('kill_chain_phases.phase_name', '=', 'initial-access')])))
```

The result of this _should_ be 19 since there are [19 attack-patterns](https://attack.mitre.org/tactics/TA0001/) (9 techniques, 10 sub-techniques) in the initial access tactic of the enterprise domain of ATT&CK.

Run on v2.2.2, this produces the expected output (albiet with a warning):
```
$ pip3 install taxii2-client==2.2.2
[...]
Successfully installed taxii2-client-2.2.2

$ python3 test_taxii.py
[taxii2client.common] [WARNING ] [2021-09-22 11:59:15,172] TAXII Server Response did not include 'Content-Range' header - results could be incomplete
19
```
Run on v2.3.0, this produces a wildly large number of attack-patterns:
```
$ pip3 install taxii2-client==2.3.0
[...]
Successfully installed taxii2-client-2.3.0

$ python3 test_taxii.py
[taxii2client.v20] [WARNING ] [2021-09-22 12:04:04,859] TAXII Server Response did not include 'Content-Range' header - results could be incomplete.
[taxii2client.v20] [WARNING ] [2021-09-22 12:04:04,879] TAXII Server Response with different amount of objects! Setting per_request=692
692
```

This count is the full quantity of attack-patterns in the knowledge base (that would be retrieved with the following query):
```python
print(len(tc_src.query([Filter('type','=', 'attack-pattern')])))
```

So it appears that the Filter by `kill_chain_phases` is being ignored in v2.3.0 of this library.

**Comment by chisholm** [comment] 2021-09-22 21:03
Your example involves both this library and the stix2 library, so it's not strictly a test case for this library.  The `kill_chain_phases` filter should not be handled by this library (since TAXII only supports filtering based on a certain small subset of STIX object properties).  When you use stix2 library `Filter` based filters with TAXII, the stix2 library must divide the filtering job between TAXII and the stix2 library itself.  So a correct result depends on the interaction between both libraries.

What ought to happen in this case is that the `type` filter *only* ought to be passed off to TAXII (via this library).  So cti-taxii-client should produce 692 results.  That would be correct behavior.

You got different behavior by changing only the version of the cti-taxii-client library, but I wonder if it's because of different interactions with the stix2 library.  What version of the stix2 library are you using?  I have not been able to reproduce this, but I am using the master branch stix2 library, and there have been recent fixes made to `TAXIICollectionSource` which are related to filtering, e.g. PR's 526 and 528.  I think these fixes have not made it into a library release yet.

**Comment by chisholm** [comment] 2021-09-22 21:11
Update: I just tried with stix2 v3.0.0 and then I was able to reproduce the error.  So I think this is really a stix2 bug which has already been fixed, probably in https://github.com/oasis-open/cti-python-stix2/pull/526 .

**Comment by clenk** [comment] 2021-09-24 13:44
stix2 v3.0.1 has been released so I'm closing this issue, but let us know if the problem persists.

**Closed by clenk** 2021-09-24 13:44 UTC
